import { PoseDefinition } from '../../../pose/types';
import { BodyPart } from 'solarxr-protocol';

const siddhasana: PoseDefinition = {
  name: 'Siddhasana',
  description: 'Siddhasana (Accomplished Pose) — seated cross-legged, spine tall, hands resting on the knees',
  requiredJoints: [
    BodyPart.HEAD,
    BodyPart.NECK,
    BodyPart.CHEST,
    BodyPart.WAIST,
    BodyPart.HIP,
    BodyPart.LEFT_UPPER_ARM,
    BodyPart.LEFT_LOWER_ARM,
    BodyPart.RIGHT_UPPER_ARM,
    BodyPart.RIGHT_LOWER_ARM,
    BodyPart.LEFT_UPPER_LEG,
    BodyPart.LEFT_LOWER_LEG,
    BodyPart.LEFT_FOOT,
    BodyPart.RIGHT_UPPER_LEG,
    BodyPart.RIGHT_LOWER_LEG,
    BodyPart.RIGHT_FOOT,
  ],
  referenceRotations: {
    [BodyPart.HEAD]:             { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.NECK]:             { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.CHEST]:            { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.UPPER_CHEST]:      { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.WAIST]:            { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.HIP]:              { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.LEFT_UPPER_LEG]:   { x: 0.635, y: -0.101, z: 0.120, w: 0.757 },
    [BodyPart.LEFT_LOWER_LEG]:   { x: -0.378, y: -0.153, z: -0.034, w: 0.913 },
    [BodyPart.LEFT_FOOT]:        { x: 0.086, y: -0.151, z: 0.040, w: 0.984 },
    [BodyPart.RIGHT_UPPER_LEG]:  { x: 0.635, y: 0.101, z: -0.120, w: 0.757 },
    [BodyPart.RIGHT_LOWER_LEG]:  { x: -0.378, y: 0.153, z: 0.034, w: 0.913 },
    [BodyPart.RIGHT_FOOT]:       { x: 0.086, y: 0.151, z: -0.040, w: 0.984 },
    [BodyPart.LEFT_UPPER_ARM]:   { x: 0.298, y: 0.039, z: 0.124, w: 0.946 },
    [BodyPart.LEFT_LOWER_ARM]:   { x: -0.458, y: -0.060, z: 0.116, w: 0.879 },
    [BodyPart.RIGHT_UPPER_ARM]:  { x: 0.298, y: -0.039, z: -0.124, w: 0.946 },
    [BodyPart.RIGHT_LOWER_ARM]:  { x: -0.458, y: 0.060, z: -0.116, w: 0.879 },
  },
  jointWeights: {
    [BodyPart.HEAD]: 1.0,
    [BodyPart.NECK]: 0.6,
    [BodyPart.CHEST]: 1.5,
    [BodyPart.WAIST]: 1.5,
    [BodyPart.HIP]: 1.0,
    [BodyPart.LEFT_UPPER_ARM]: 0.5,
    [BodyPart.LEFT_LOWER_ARM]: 0.4,
    [BodyPart.RIGHT_UPPER_ARM]: 0.5,
    [BodyPart.RIGHT_LOWER_ARM]: 0.4,
    [BodyPart.LEFT_UPPER_LEG]: 0.8,
    [BodyPart.LEFT_LOWER_LEG]: 0.6,
    [BodyPart.LEFT_FOOT]: 0.4,
    [BodyPart.RIGHT_UPPER_LEG]: 0.8,
    [BodyPart.RIGHT_LOWER_LEG]: 0.6,
    [BodyPart.RIGHT_FOOT]: 0.4,
  },
  jointTolerances: {
    [BodyPart.HEAD]: 0.35,
    [BodyPart.NECK]: 0.30,
    [BodyPart.CHEST]: 0.25,
    [BodyPart.WAIST]: 0.25,
    [BodyPart.HIP]: 0.30,
    [BodyPart.LEFT_UPPER_ARM]: 0.50,
    [BodyPart.LEFT_LOWER_ARM]: 0.50,
    [BodyPart.RIGHT_UPPER_ARM]: 0.50,
    [BodyPart.RIGHT_LOWER_ARM]: 0.50,
    [BodyPart.LEFT_UPPER_LEG]: 0.55,
    [BodyPart.LEFT_LOWER_LEG]: 0.55,
    [BodyPart.LEFT_FOOT]: 0.55,
    [BodyPart.RIGHT_UPPER_LEG]: 0.55,
    [BodyPart.RIGHT_LOWER_LEG]: 0.55,
    [BodyPart.RIGHT_FOOT]: 0.55,
  },
  minimumScore: 0.70,
  holdDuration: 5,
  hints: {
    [BodyPart.HEAD]: 'Keep head level',
    [BodyPart.NECK]: 'Lengthen neck upward',
    [BodyPart.CHEST]: 'Lift chest, sit tall',
    [BodyPart.WAIST]: 'Keep spine straight',
    [BodyPart.HIP]: 'Level the hips',
    [BodyPart.LEFT_UPPER_ARM]: 'Rest left arm on knee',
    [BodyPart.LEFT_LOWER_ARM]: 'Relax left forearm on knee',
    [BodyPart.RIGHT_UPPER_ARM]: 'Rest right arm on knee',
    [BodyPart.RIGHT_LOWER_ARM]: 'Relax right forearm on knee',
    [BodyPart.LEFT_UPPER_LEG]: 'Fold left thigh in',
    [BodyPart.LEFT_LOWER_LEG]: 'Tuck left shin under',
    [BodyPart.LEFT_FOOT]: 'Rest left foot near shin',
    [BodyPart.RIGHT_UPPER_LEG]: 'Fold right thigh in',
    [BodyPart.RIGHT_LOWER_LEG]: 'Tuck right shin under',
    [BodyPart.RIGHT_FOOT]: 'Rest right foot near shin',
  },
};

export default siddhasana;
