import { PoseDefinition } from '../../../pose/types';
import { BodyPart } from 'solarxr-protocol';

const vrikshasana: PoseDefinition = {
  name: 'Vrikshasana',
  description: 'Tree Pose — balance on one leg, other foot on inner thigh, hands together overhead',
  requiredJoints: [
    BodyPart.HEAD,
    BodyPart.NECK,
    BodyPart.CHEST,
    BodyPart.WAIST,
    BodyPart.HIP,
    BodyPart.LEFT_UPPER_ARM,
    BodyPart.LEFT_LOWER_ARM,
    BodyPart.RIGHT_UPPER_ARM,
    BodyPart.RIGHT_LOWER_ARM,
    BodyPart.LEFT_UPPER_LEG,
    BodyPart.LEFT_LOWER_LEG,
    BodyPart.LEFT_FOOT,
    BodyPart.RIGHT_UPPER_LEG,
    BodyPart.RIGHT_LOWER_LEG,
    BodyPart.RIGHT_FOOT,
  ],
  referenceRotations: {
    [BodyPart.HEAD]:             { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.NECK]:             { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.CHEST]:            { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.WAIST]:            { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.HIP]:              { x: 0, y: 0, z: 0, w: 1 },
    // Standing (left) leg: straight down
    [BodyPart.LEFT_UPPER_LEG]:   { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.LEFT_LOWER_LEG]:   { x: 0, y: 0, z: 0, w: 1 },
    [BodyPart.LEFT_FOOT]:        { x: 0, y: 0, z: 0, w: 1 },
    // Raised (right) leg: knee bent outward ~80°, foot resting on inner thigh
    [BodyPart.RIGHT_UPPER_LEG]:  { x: -0.342, y: -0.306, z: 0.410, w: 0.796 },
    [BodyPart.RIGHT_LOWER_LEG]:  { x: 0.270, y: 0.431, z: -0.147, w: 0.849 },
    [BodyPart.RIGHT_FOOT]:       { x: 0.171, y: 0.105, z: -0.163, w: 0.964 },
    // Arms overhead: ~180° forward rotation from hanging
    [BodyPart.LEFT_UPPER_ARM]:   { x: -0.653, y: 0.271, z: -0.271, w: 0.653 },
    [BodyPart.LEFT_LOWER_ARM]:   { x: -0.653, y: 0.271, z: -0.271, w: 0.653 },
    [BodyPart.RIGHT_UPPER_ARM]:  { x: -0.653, y: -0.271, z: 0.271, w: 0.653 },
    [BodyPart.RIGHT_LOWER_ARM]:  { x: -0.653, y: -0.271, z: 0.271, w: 0.653 },
  },
  jointWeights: {
    [BodyPart.HEAD]: 1.0,
    [BodyPart.NECK]: 0.6,
    [BodyPart.CHEST]: 1.5,
    [BodyPart.WAIST]: 1.5,
    [BodyPart.HIP]: 1.0,
    [BodyPart.LEFT_UPPER_ARM]: 0.7,
    [BodyPart.LEFT_LOWER_ARM]: 0.5,
    [BodyPart.RIGHT_UPPER_ARM]: 0.7,
    [BodyPart.RIGHT_LOWER_ARM]: 0.5,
    [BodyPart.LEFT_UPPER_LEG]: 1.0,
    [BodyPart.LEFT_LOWER_LEG]: 0.7,
    [BodyPart.LEFT_FOOT]: 0.4,
    [BodyPart.RIGHT_UPPER_LEG]: 1.0,
    [BodyPart.RIGHT_LOWER_LEG]: 0.7,
    [BodyPart.RIGHT_FOOT]: 0.4,
  },
  jointTolerances: {
    [BodyPart.HEAD]: 0.40,
    [BodyPart.NECK]: 0.35,
    [BodyPart.CHEST]: 0.30,
    [BodyPart.WAIST]: 0.30,
    [BodyPart.HIP]: 0.35,
    [BodyPart.LEFT_UPPER_ARM]: 0.50,
    [BodyPart.LEFT_LOWER_ARM]: 0.50,
    [BodyPart.RIGHT_UPPER_ARM]: 0.50,
    [BodyPart.RIGHT_LOWER_ARM]: 0.50,
    [BodyPart.LEFT_UPPER_LEG]: 0.40,
    [BodyPart.LEFT_LOWER_LEG]: 0.40,
    [BodyPart.LEFT_FOOT]: 0.40,
    [BodyPart.RIGHT_UPPER_LEG]: 0.60,
    [BodyPart.RIGHT_LOWER_LEG]: 0.60,
    [BodyPart.RIGHT_FOOT]: 0.60,
  },
  minimumScore: 0.70,
  holdDuration: 5,
  hints: {
    [BodyPart.HEAD]: 'Keep head upright',
    [BodyPart.NECK]: 'Straighten neck',
    [BodyPart.CHEST]: 'Pull chest upright',
    [BodyPart.WAIST]: 'Engage core',
    [BodyPart.HIP]: 'Level hips',
    [BodyPart.LEFT_UPPER_ARM]: 'Raise left arm overhead',
    [BodyPart.LEFT_LOWER_ARM]: 'Straighten left arm',
    [BodyPart.RIGHT_UPPER_ARM]: 'Raise right arm overhead',
    [BodyPart.RIGHT_LOWER_ARM]: 'Straighten right arm',
    [BodyPart.LEFT_UPPER_LEG]: 'Stand firm on left leg',
    [BodyPart.LEFT_LOWER_LEG]: 'Straighten left knee',
    [BodyPart.LEFT_FOOT]: 'Plant left foot flat',
    [BodyPart.RIGHT_UPPER_LEG]: 'Bend right knee outward',
    [BodyPart.RIGHT_LOWER_LEG]: 'Place right foot on inner thigh',
    [BodyPart.RIGHT_FOOT]: 'Press right foot into thigh',
  },
};

export default vrikshasana;
